CREATE TABLE univet_environment (
 id integer PRIMARY KEY CHECK(id=1), environment text NOT NULL
 CHECK(environment IN ('development','test','demo','production'))
);
CREATE TABLE usuarios (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 login text NOT NULL UNIQUE, senha_hash text NOT NULL, access_code_hash text,
 nome text NOT NULL, perfil text NOT NULL DEFAULT 'veterinaria' CHECK(perfil IN ('admin','veterinaria')),
 ativo smallint NOT NULL DEFAULT 1 CHECK(ativo IN (0,1)),
 session_version integer NOT NULL DEFAULT 0,
 must_change_password smallint NOT NULL DEFAULT 0 CHECK(must_change_password IN (0,1)),
 ultimo_acesso timestamptz
);
CREATE TABLE tutores (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome text NOT NULL, telefone text NOT NULL, cpf text UNIQUE, endereco text
);
CREATE TABLE especies (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome text NOT NULL UNIQUE, parent_id bigint REFERENCES especies(id) ON DELETE RESTRICT
);
CREATE TABLE racas (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome text NOT NULL, especie_id bigint NOT NULL REFERENCES especies(id) ON DELETE RESTRICT,
 UNIQUE(nome,especie_id), UNIQUE(id,especie_id)
);
CREATE TABLE veterinarios (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome text NOT NULL UNIQUE
);
CREATE TABLE servicos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome text NOT NULL UNIQUE, duracao_minutos integer NOT NULL CHECK(duracao_minutos BETWEEN 20 AND 1440)
);
CREATE TABLE pets (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome text NOT NULL, especie text NOT NULL, raca text, idade text, historico text,
 tutor_id bigint NOT NULL REFERENCES tutores(id) ON DELETE RESTRICT,
 especie_id bigint REFERENCES especies(id) ON DELETE RESTRICT,
 raca_id bigint REFERENCES racas(id) ON DELETE RESTRICT,
 FOREIGN KEY(raca_id,especie_id) REFERENCES racas(id,especie_id) ON DELETE RESTRICT
);
CREATE TABLE consultas (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 data_hora timestamp NOT NULL, data_fim timestamp,
 pet_id bigint NOT NULL REFERENCES pets(id) ON DELETE RESTRICT,
 observacoes text, status text NOT NULL CHECK(status IN ('Agendada','Concluida','Cancelada')),
 tipo_consulta text DEFAULT 'Consulta de rotina',
 confirmacao_status text DEFAULT 'Pendente' CHECK(confirmacao_status IN ('Pendente','Confirmada','Nao confirmada')),
 servico_id bigint REFERENCES servicos(id) ON DELETE RESTRICT,
 duracao_total_minutos integer DEFAULT 20 CHECK(duracao_total_minutos BETWEEN 20 AND 1440),
 veterinario_id bigint REFERENCES veterinarios(id) ON DELETE RESTRICT,
 tipo_atendimento text DEFAULT 'Presencial' CHECK(tipo_atendimento IN ('Presencial','Domiciliar')),
 diagnostico text, tratamento text, vacinas text,
 CHECK(data_fim IS NULL OR data_fim>data_hora)
);
CREATE TABLE historico_alteracoes (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 entidade text NOT NULL, registro_id bigint NOT NULL, acao text NOT NULL,
 usuario_nome text NOT NULL, dados_json text NOT NULL, criado_em timestamptz NOT NULL
);
CREATE TABLE condicoes_clinicas (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 pet_id bigint NOT NULL REFERENCES pets(id) ON DELETE RESTRICT,
 condicao text NOT NULL, observacoes text,
 status text NOT NULL DEFAULT 'Ativa' CHECK(status IN ('Ativa','Controlada','Resolvida')),
 registrado_em timestamptz NOT NULL, usuario_nome text NOT NULL
);
CREATE TABLE categorias (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome text NOT NULL UNIQUE, descricao text,
 ativo smallint NOT NULL DEFAULT 1 CHECK(ativo IN (0,1)), criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE fornecedores (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome text NOT NULL UNIQUE, documento text, telefone text, email text, endereco text,
 ativo smallint NOT NULL DEFAULT 1 CHECK(ativo IN (0,1)), criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE produtos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome text NOT NULL, codigo text UNIQUE,
 tipo text NOT NULL CHECK(tipo IN ('Medicamento','Vacina','Material','Produto')),
 categoria_id bigint REFERENCES categorias(id) ON DELETE SET NULL,
 unidade_medida text NOT NULL DEFAULT 'unidade',
 estoque_minimo numeric(18,6) NOT NULL DEFAULT 0 CHECK(estoque_minimo BETWEEN 0 AND 1000000000),
 margem_lucro_percentual numeric(9,4) NOT NULL DEFAULT 30 CHECK(margem_lucro_percentual BETWEEN 0 AND 10000),
 ativo smallint NOT NULL DEFAULT 1 CHECK(ativo IN (0,1)), criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE lotes (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 produto_id bigint NOT NULL REFERENCES produtos(id) ON DELETE RESTRICT,
 fornecedor_id bigint REFERENCES fornecedores(id) ON DELETE SET NULL,
 numero_lote text NOT NULL,
 quantidade_inicial numeric(18,6) NOT NULL CHECK(quantidade_inicial>0 AND quantidade_inicial<=1000000000),
 quantidade_atual numeric(18,6) NOT NULL CHECK(quantidade_atual BETWEEN 0 AND 1000000000),
 validade date, data_entrada date NOT NULL,
 valor_compra_unitario numeric(18,2) NOT NULL DEFAULT 0 CHECK(valor_compra_unitario BETWEEN 0 AND 1000000000),
 valor_venda_sugerido_unitario numeric(18,2) NOT NULL DEFAULT 0 CHECK(valor_venda_sugerido_unitario BETWEEN 0 AND 1000000000),
 ativo smallint NOT NULL DEFAULT 1 CHECK(ativo IN (0,1)), criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(produto_id,numero_lote), UNIQUE(id,produto_id)
);
CREATE TABLE movimentacoes_estoque (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 produto_id bigint NOT NULL REFERENCES produtos(id) ON DELETE RESTRICT,
 lote_id bigint NOT NULL REFERENCES lotes(id) ON DELETE RESTRICT,
 tipo text NOT NULL CHECK(tipo IN ('Entrada','Saída','Ajuste','Estorno')),
 quantidade numeric(18,6) NOT NULL CHECK(quantidade>0 AND quantidade<=1000000000),
 quantidade_variacao numeric(18,6) NOT NULL CHECK(quantidade_variacao BETWEEN -1000000000 AND 1000000000),
 motivo text NOT NULL,
 consulta_id bigint REFERENCES consultas(id) ON DELETE RESTRICT,
 usuario_id bigint REFERENCES usuarios(id) ON DELETE RESTRICT,
 movimentacao_origem_id bigint REFERENCES movimentacoes_estoque(id) ON DELETE RESTRICT,
 valor_unitario_sugerido numeric(18,2) CHECK(valor_unitario_sugerido BETWEEN 0 AND 1000000000),
 valor_unitario_praticado numeric(18,2) CHECK(valor_unitario_praticado BETWEEN 0 AND 1000000000),
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(lote_id,produto_id) REFERENCES lotes(id,produto_id) ON DELETE RESTRICT,
 UNIQUE(id,lote_id,produto_id,consulta_id),
 CHECK((tipo='Estorno') = (movimentacao_origem_id IS NOT NULL)),
 CHECK(abs(quantidade_variacao)=quantidade),
 CHECK(tipo!='Saída' OR quantidade_variacao<0),
 CHECK(tipo!='Entrada' OR quantidade_variacao>0)
);
CREATE TABLE itens_consulta (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 consulta_id bigint NOT NULL REFERENCES consultas(id) ON DELETE RESTRICT,
 produto_id bigint NOT NULL REFERENCES produtos(id) ON DELETE RESTRICT,
 lote_id bigint NOT NULL REFERENCES lotes(id) ON DELETE RESTRICT,
 quantidade numeric(18,6) NOT NULL CHECK(quantidade>0 AND quantidade<=1000000000),
 movimentacao_id bigint NOT NULL REFERENCES movimentacoes_estoque(id) ON DELETE RESTRICT,
 usuario_id bigint REFERENCES usuarios(id) ON DELETE RESTRICT,
 valor_unitario_sugerido numeric(18,2) CHECK(valor_unitario_sugerido BETWEEN 0 AND 1000000000),
 valor_unitario_praticado numeric(18,2) CHECK(valor_unitario_praticado BETWEEN 0 AND 1000000000),
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(lote_id,produto_id) REFERENCES lotes(id,produto_id) ON DELETE RESTRICT,
 FOREIGN KEY(movimentacao_id,lote_id,produto_id,consulta_id) REFERENCES movimentacoes_estoque(id,lote_id,produto_id,consulta_id) ON DELETE RESTRICT,
 UNIQUE(movimentacao_id)
);
CREATE TABLE auth_sessions (
 token_hash text PRIMARY KEY, usuario_id bigint NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
 version integer NOT NULL, expires_at double precision NOT NULL, last_seen double precision NOT NULL
);
CREATE TABLE rate_limits (key text PRIMARY KEY, expires_at double precision NOT NULL, hits integer NOT NULL);
CREATE TABLE security_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 usuario_id bigint REFERENCES usuarios(id) ON DELETE RESTRICT,
 evento text NOT NULL, criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE schema_migrations (version text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO schema_migrations(version) VALUES ('20260919_security_v1');
CREATE UNIQUE INDEX idx_estorno_unico_origem ON movimentacoes_estoque(movimentacao_origem_id) WHERE tipo='Estorno';
CREATE UNIQUE INDEX idx_consulta_inicio_vet ON consultas(veterinario_id,data_hora) WHERE status!='Cancelada';
CREATE INDEX idx_pets_tutor ON pets(tutor_id);
CREATE INDEX idx_consultas_pet ON consultas(pet_id);
CREATE INDEX idx_consultas_veterinario_periodo ON consultas(veterinario_id,data_hora,data_fim);
CREATE INDEX idx_historico_entidade_registro ON historico_alteracoes(entidade,registro_id,criado_em);
CREATE INDEX idx_condicoes_pet_status ON condicoes_clinicas(pet_id,status,registrado_em);
CREATE INDEX idx_produtos_categoria ON produtos(categoria_id);
CREATE INDEX idx_produtos_tipo_ativo ON produtos(tipo,ativo);
CREATE INDEX idx_lotes_produto_validade ON lotes(produto_id,validade,quantidade_atual);
CREATE INDEX idx_lotes_fornecedor ON lotes(fornecedor_id);
CREATE INDEX idx_movimentacoes_produto_data ON movimentacoes_estoque(produto_id,criado_em);
CREATE INDEX idx_movimentacoes_lote ON movimentacoes_estoque(lote_id);
CREATE INDEX idx_movimentacoes_consulta ON movimentacoes_estoque(consulta_id);
CREATE INDEX idx_itens_consulta ON itens_consulta(consulta_id);
